#! /bin/sh
# /etc/init.d/integratioWWebServer 

### BEGIN INIT INFO
# Provides:          Integratio - Base Web Server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start Integratio Web Server at boot (https://github.com/zupino/tcz)
# Description:       This script allow to automatically startup the Integratio Web Server (see https://github.com/zupino/tcz). The script to launch the server was taken from http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    # TODO Need to check if a correction in the routing is needed here
    echo "Starting Integratio - Base Web Server"
    #  First we need to block the RST from kernel
    iptables -A OUTPUT -p tcp --tcp-flags RST RST -j DROP
    /home/pi/tcz/integratioWebServer.py
    ;;
  stop)
    echo "Stopping Integratio Web Server"
    # Removing the iptable rule to block kernel RST
    iptables -D OUTPUT -p tcp --tcp-flags RST RST -j DROP
    killall "integratioWebServer.py"
    ;;
  *)
    echo "Usage: /etc/init.d/integratioWebServer {start|stop}"
    exit 1
    ;;
esac

exit 0
