#! /bin/sh

# TCZee - Scapy-based TCP stack basic implementation for network testing 
# Copyright (C) 2015555555555555555555555555555555555555555555555555555555 Marco Zunino

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# A copy of the full GNU General Public License is available in 
# the LICENSE file in the root folder of the original projecti
# hosted on 'https://github.com/zupino/tcz'.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# This file is part of the Integratio Project, a framework prepared to run on
# development board as RaspberryPi or BeagleBone to create a black box system integration tool
# aimed to create network error condition or corner case not possible to reproduce on real
# environment.

# This is a init.d script, but it did not work finally in my case with RPi
# 
# 1. place this script in the /etc/init.d/ folder
# 2. Make sure that the path to the python script are ok
# 3. verify the correct function of the script by running the command sudo service integratioService start, check also the stop 
# 4. add the script to the automatic startup sequence with the command sudo update-rc integratioService defaults
# 5. Eventually, if you need to remove the script, use the same command as before, but with the remove option

### BEGIN INIT INFO
# Provides:          Integratio - Base Web Server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start Integratio Web Server at boot (https://github.com/zupino/tcz)
# Description:       This script allow to automatically startup the Integratio Web Server (see https://github.com/zupino/tcz). The script to launch the server was taken from http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    # TODO Need to check if a correction in the routing is needed here
    echo "Starting Integratio - Base Web Server"
    #  First we need to block the RST from kernel
    iptables -A OUTPUT -p tcp --tcp-flags RST RST -j DROP
    /home/pi/tcz/integratioWebServer.py
    ;;
  stop)
    echo "Stopping Integratio Web Server"
    # Removing the iptable rule to block kernel RST
    iptables -D OUTPUT -p tcp --tcp-flags RST RST -j DROP
    killall "integratioWebServer.py"
    ;;
  *)
    echo "Usage: /etc/init.d/integratioWebServer {start|stop}"
    exit 1
    ;;
esac

exit 0
